fix(modal): tooltip bug scroll
klever-io/kleverscan pull request #14
Opened 2023-10-24 14:34 UTC by JoseToitio

2023-10-26 19:29 UTC, Doug-Fernando commented
Check mobile
![image](https://github.com/klever-io/kleverscan/assets/72462482/5d6a7b95-3319-476f-98de-b9e60b40af52)

Add a padding 
![image](https://github.com/klever-io/kleverscan/assets/72462482/9904c262-4375-4f7f-a716-c5272e704675)
![image](https://github.com/klever-io/kleverscan/assets/72462482/4d0958b2-afd3-48c6-9f61-7e9ab5488d31)

2023-10-26 19:29 UTC, Doug-Fernando requested changes
check comments

2023-10-27 18:10 UTC, lucasportella approved these changes

2023-10-27 19:35 UTC, Doug-Fernando approved these changes

2023-10-27 19:35 UTC, merged