Kc 1970 tanstack query refactor pages 6 8
klever-io/kleverscan pull request #19
Opened 2023-10-26 18:39 UTC by JoseToitio

2023-10-27 19:12 UTC, lucasportella requested changes

2023-10-27 19:12 UTC, lucasportella commented on src/pages/itos/index.tsx
> +    async ({ pageParam = 1 }) => {
too complex, this should be a separated function.

2023-10-27 19:12 UTC, lucasportella commented on src/pages/itos/index.tsx
> +      getNextPageParam: lastPage => {
same here

2023-10-27 19:12 UTC, lucasportella commented on src/pages/itos/index.tsx
> +  const itemsITOs = useMemo(() => {
dont use useMemo for iterations below 1k items. Consider reading [here](https://react.dev/learn/you-might-not-need-an-effect#how-to-tell-if-a-calculation-is-expensive)

2023-10-27 19:12 UTC, lucasportella commented on src/services/requests/ito/index.ts
> +  if (data) {
consider checking the length of the data, since it returns an object, will always be true

2023-10-31 20:25 UTC, lucasportella approved these changes

2023-11-06 09:07 UTC, Doug-Fernando approved these changes

2023-11-06 09:07 UTC, merged