fix: fix console errors
klever-io/kleverscan pull request #23
Opened 2023-10-27 19:31 UTC by Doug-Fernando

2023-10-27 20:41 UTC, lucasportella commented
can you tell me which console errors this fixes and where they occur?

2023-11-06 09:28 UTC, Doug-Fernando commented
Home page
![image](https://github.com/klever-io/kleverscan/assets/72462482/98e3a93f-546f-4305-84d6-e42d0694de21)
![image](https://github.com/klever-io/kleverscan/assets/72462482/6c7377b5-7af7-4882-83df-3049f956712a)
![image](https://github.com/klever-io/kleverscan/assets/72462482/7afded02-8a3e-42e5-b8aa-c401289c4987)
![image](https://github.com/klever-io/kleverscan/assets/72462482/0bba0da7-8fd2-4aef-aa58-6b0bfbb6f7d3)
![image](https://github.com/klever-io/kleverscan/assets/72462482/7874d762-449d-47c8-99aa-eb9ecde5ff82)
![image](https://github.com/klever-io/kleverscan/assets/72462482/286090f6-040d-46fb-98ae-f672dcbd19d4)
![image](https://github.com/klever-io/kleverscan/assets/72462482/4801e0f7-3a68-460d-ad9a-9ea25313a2ee)

2023-11-06 09:30 UTC, Doug-Fernando commented
Blocks Page
![image](https://github.com/klever-io/kleverscan/assets/72462482/0a355ab0-3bba-4cb9-9656-71e36576d06a)
![image](https://github.com/klever-io/kleverscan/assets/72462482/0106c38c-6497-46dd-a443-a81e1b01cd32)

2023-11-06 09:32 UTC, Doug-Fernando commented
Transactions Page
![image](https://github.com/klever-io/kleverscan/assets/72462482/cb96b93f-610d-4132-8304-0b535511647f)
![image](https://github.com/klever-io/kleverscan/assets/72462482/d13bc8ca-65ab-472d-863a-78dedbd6d27d)

2023-11-06 09:33 UTC, Doug-Fernando commented
Assets Page
![image](https://github.com/klever-io/kleverscan/assets/72462482/e1edf4ef-e131-4625-bcda-f0a16e711dfc)
![image](https://github.com/klever-io/kleverscan/assets/72462482/f43e4602-0b6a-4886-8b2a-e578e520623f)

2023-11-06 09:34 UTC, Doug-Fernando commented
Marketplaces Page
![image](https://github.com/klever-io/kleverscan/assets/72462482/58eee79d-77df-4ed9-aaa7-eb4809d84fb6)

2023-11-06 12:16 UTC, samufacanha2 requested changes
check comment

2023-11-06 12:16 UTC, samufacanha2 commented on src/components/InputGlobal/index.tsx
> +    // setOpenSearch: setOpenSearch,
either remove or keep the line, don't comment it

2023-11-06 19:27 UTC, samufacanha2 approved these changes

2023-11-06 19:37 UTC, lucasportella approved these changes

2023-11-06 19:37 UTC, merged