Kc 2085 align search pop up usage with design
klever-io/kleverscan pull request #28
Opened 2023-10-30 20:28 UTC by JoseToitio

2023-11-01 17:37 UTC, lucasportella requested changes

2023-11-01 17:37 UTC, lucasportella commented on src/components/InputGlobal/index.tsx
> +    setSearch(event.target.value.trim().toLowerCase());
need to add debounce function

2023-11-01 17:37 UTC, lucasportella commented on src/components/InputGlobal/index.tsx
> +  const [linkPage, setLinkPage] = useState('');
is there another user action that needs to be monitored besides the text input or mouse focus in/out of the pop up? if not, just create a variable that stores the data you want to save

2023-11-01 17:37 UTC, lucasportella commented on src/components/InputGlobal/index.tsx
> +      // if (inputRef.current !== null) inputRef.current.value = '';
delete comment?

2023-11-01 17:37 UTC, lucasportella commented on src/components/PrePageTooltip/RowSections/index.tsx
> +            <TitleSpan>Block Summaryy</TitleSpan>
typo

2023-11-01 17:37 UTC, lucasportella commented on src/components/InputGlobal/index.tsx
> +    setShowTooltip(true);
should not set tooltip to true just by clicking in input box, makes no sense:
![image](https://github.com/klever-io/kleverscan/assets/63923113/a348220b-eefa-42ab-b0f3-c3a986e0b8b3)

2023-11-03 14:10 UTC, lucasportella commented on src/components/InputGlobal/index.tsx
> +    setSearch(event.target.value);
this does not solve excessive user requests, must add debounce fn

2023-11-03 14:12 UTC, lucasportella requested changes
must discuss problems in PR time

2023-11-03 14:12 UTC, lucasportella commented on src/components/PrePageTooltip/RowSections/index.tsx
> +export const setSessionStorage = (link: string): void => {
i'm not very sure if this is really necessary. Let's discuss this in PR time

2023-11-16 15:09 UTC, lucasportella approved these changes

2023-11-17 17:52 UTC, Doug-Fernando approved these changes

2023-11-17 17:52 UTC, merged