feat: :sparkles: Add more info on the KDA Staking tab
klever-io/kleverscan pull request #313
Opened 2024-08-14 20:26 UTC by saviojks

2024-08-14 20:29 UTC, lucasportella requested changes

2024-08-14 20:29 UTC, lucasportella commented on public/locales/en/assets.json
> +    "Qtd_Holders": "Qtd Holders",
shot not be in Qty or Quantity?

2024-08-14 20:29 UTC, lucasportella commented on public/locales/pt-BR/assets.json
> +    "Qtd_Holders": "Qtd Holders",
same

2024-08-14 20:43 UTC, lucasportella commented on public/locales/pt-BR/assets.json
> +    "Qtd_Holders": "Qtd Holders",
here only the property, the value i think should be Quantidade de holders

2024-08-15 11:14 UTC, saviojks commented on public/locales/en/assets.json
> +    "Qtd_Holders": "Qtd Holders",
Done

2024-08-15 11:51 UTC, lucasportella approved these changes

2024-08-15 11:51 UTC, merged