Kc 2129 resize observer loop with unresolved notifications bugsnag
klever-io/kleverscan pull request #36
Opened 2023-11-06 23:53 UTC by JoseToitio

2023-11-07 13:10 UTC, samufacanha2 requested changes

2023-11-07 13:10 UTC, samufacanha2 commented on src/components/AccountDetailsModal/index.tsx
>        if (storagePrimaryAssets) {
use guard clause to improve the conditional flow
https://deviq.com/design-patterns/guard-clause

2023-11-07 13:10 UTC, samufacanha2 commented on src/components/AccountDetailsModal/index.tsx
> +        if (newPrimaryAsset[0]) {
here too

2023-11-08 13:12 UTC, samufacanha2 approved these changes

2023-11-08 14:11 UTC, Doug-Fernando approved these changes

2023-11-08 14:13 UTC, merged