Kc 2088 feedback improvements wizard
klever-io/kleverscan pull request #5
Opened 2023-10-18 20:44 UTC by JoseToitio

2023-10-20 20:42 UTC, lucasportella requested changes
1-add border radius:
![image](https://github.com/klever-io/kleverscan/assets/63923113/dde6ca68-c390-4c91-9d39-9e753831a318)
![image](https://github.com/klever-io/kleverscan/assets/63923113/e48c9a60-e146-46b5-b648-2901dc4a3b9a)

2-white border from arrow is distorted:
![image](https://github.com/klever-io/kleverscan/assets/63923113/2b162207-681f-40c6-94b0-3888cca1a1e8)
![image](https://github.com/klever-io/kleverscan/assets/63923113/958ecfda-026b-42ea-8401-5456ba47909d)

3-should only accept numbers and add number mask:
![image](https://github.com/klever-io/kleverscan/assets/63923113/3e1feb11-deee-49d9-bd52-f1efbe1bfdf4)
![image](https://github.com/klever-io/kleverscan/assets/63923113/111fac12-59e6-4c31-9bad-8730683cb6ef)

4-ball needs to be more to the right/left:
![image](https://github.com/klever-io/kleverscan/assets/63923113/a08f9877-0612-4e0d-b8f8-b98afaa72d99)

5-fix overflow of green icon; next button should be blocked regardless of the selected option if user is not connected; change not connected disclaimer to a warning color:
![image](https://github.com/klever-io/kleverscan/assets/63923113/5f33558c-9cd2-4db5-a375-fa599b9bb331)

2023-10-27 15:58 UTC, lucasportella requested changes
1- X solto se usuário não tem wallet address(alterna de uma opção para outro):
![image](https://github.com/klever-io/kleverscan/assets/63923113/f408c3f6-7308-4704-9d83-30e31458e780)

2023-10-31 20:09 UTC, lucasportella approved these changes

2023-11-01 14:09 UTC, Doug-Fernando approved these changes

2023-11-01 14:09 UTC, merged