refactor: change home to fetch with react query
klever-io/kleverscan pull request #8
Opened 2023-10-19 21:55 UTC by Doug-Fernando

2023-10-23 13:22 UTC, samufacanha2 requested changes

2023-10-23 13:22 UTC, samufacanha2 commented on src/components/Cards/CoinDataFetcher/CoinCard/index.tsx
> +                coinDays.current.KLV = 0;
manually setting ref instead of refetching coins

2023-11-01 20:07 UTC, JoseToitio approved these changes

2023-11-06 12:08 UTC, samufacanha2 requested changes
![image](https://github.com/klever-io/kleverscan/assets/39703077/f75ac794-691e-41e1-a5c1-7c947cb9c0dc)
Accounts start with value, then go to zero on second request

2023-11-08 13:07 UTC, samufacanha2 approved these changes

2023-11-08 13:07 UTC, merged